language: python
python:
    - '3.6'
    - '2.7'
install:
    - pip install keras
    - pip install tensorflow
    - pip install git+https://github.com/broadinstitute/keras-resnet
script:
    - py.test --pep8
