language: python
python:
    - '3.6'
    - '2.7'
install:
    - pip install keras==2.0.9
    - pip install tensorflow
    - pip install git+https://github.com/broadinstitute/keras-resnet
    - pip install pytest-pep8
script:
    - py.test --pep8
